/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Code;

import java.sql.*;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.util.Calendar;
import java.util.GregorianCalendar;
/**
 *
 * @author THARAKA DEVINDI
 */
public class Login extends javax.swing.JFrame {
 Connection con = null;
 ResultSet rs=null;
 PreparedStatement pst=null;

    /**
     * Creates new form Login
     */
    public Login()
    {
          try
        {  
           DBConnection obj=new DBConnection();
           con=obj.DBGetConnection();
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog( null, "Error connecting to database"+ex,"Login Form",
                    JOptionPane.ERROR_MESSAGE);
        }
        initComponents();
        
        //Display JFrame in center of screen
        
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width/2 - getWidth()/2, 
        size.height/2 - getHeight()/2);
        
        currentDate();
    }

    // Display color of panel
    
class jPanelGradient extends JPanel
{
    protected void paintComponent(Graphics g)
    {
        Graphics2D g2d = (Graphics2D)g;
        int width = getWidth();
        int height = getHeight();
        
        Color color1 = new Color(52,143,80);
        Color color2 = new Color(86,180,211);
//         Color color1 = Color.blue;
//        Color color2 = Color.cyan;
//        
        GradientPaint gp = new GradientPaint (0,0,color1,180,height,color2);
        g2d.setPaint(gp);
        g2d.fillRect(0, 0, width, height);
    }
}
    
   // Add date and time in menu bar
    
public void currentDate ()
{
        Calendar cal =new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int year = cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);
        
        lblDate.setText((month+1)+"/"+day+"/"+year);
        
        int second = cal.get(Calendar.SECOND);
        int minute = cal.get(Calendar.MINUTE);
        int hour = cal.get(Calendar.HOUR);
        
        lblTime.setText(hour+":"+(minute)+":"+second);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new jPanelGradient();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnSignIn = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnLoginAsDeveloper = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cmbDivision = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuItem_Exit = new javax.swing.JMenuItem();
        lblDate = new javax.swing.JMenu();
        lblTime = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "XYZ Organization", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Adobe Garamond Pro Bold", 3, 24), new java.awt.Color(0, 0, 0))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/person.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setText("Login Page");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("User Name");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Password");

        btnSignIn.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnSignIn.setText("Sign In");
        btnSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignInActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnLoginAsDeveloper.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnLoginAsDeveloper.setText("Login as Developer");
        btnLoginAsDeveloper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginAsDeveloperActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Division");

        cmbDivision.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cmbDivision.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "HR" }));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel6.setText("Salary Management System");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(272, 272, 272)
                            .addComponent(btnLoginAsDeveloper))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(57, 57, 57)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(46, 46, 46)
                                    .addComponent(btnSignIn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnCancel)
                                    .addGap(96, 96, 96))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel4))
                                    .addGap(106, 106, 106)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cmbDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(0, 0, Short.MAX_VALUE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 22, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbDivision, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSignIn)
                            .addComponent(btnCancel))
                        .addGap(27, 27, 27)
                        .addComponent(btnLoginAsDeveloper)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        MenuItem_Exit.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        MenuItem_Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Exit.png"))); // NOI18N
        MenuItem_Exit.setText("Exit");
        MenuItem_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem_ExitActionPerformed(evt);
            }
        });
        jMenu1.add(MenuItem_Exit);

        jMenuBar1.add(jMenu1);

        lblDate.setText("Date");
        lblDate.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jMenuBar1.add(lblDate);

        lblTime.setText("Time");
        lblTime.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jMenuBar1.add(lblTime);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignInActionPerformed
        // TODO add your handling code here:

    if (txtUsername.getText().equals("")) 
    {
        JOptionPane.showMessageDialog(null, "Username Field is empty");
    } 
    else if (txtPassword.getText().equals("")) 
    {
        JOptionPane.showMessageDialog(null, "Password Field is empty");
    }
    else 
    {
        String sql = "select * from User_Authentication Where (Username =? and Password =? and Division =?)";
        try{
           int count =0;
           
           pst=con.prepareStatement(sql);
           
           pst.setString(1,txtUsername.getText());
           pst.setString(2,txtPassword.getText());
           pst.setString(3, cmbDivision.getSelectedItem().toString());
          
           rs=pst.executeQuery();
           
           while(rs.next())
           {
            int UserId = rs.getInt(1);
               Emp.EmpId = UserId;
               String Username = rs.getString("Username");
               Emp.EmpName = Username;
           count =count+1;
           }
           
            String access=(cmbDivision.getSelectedItem().toString());
           if(access=="Admin") 
           {
           
               if(count==1){
                   JOptionPane.showMessageDialog(null,"Sucess.. WELCOME TO ADMIN MENU" );
                   AdminMenu j = new AdminMenu();
                   j.setVisible(true);
                   this.dispose();
           
           }
           else if(count>1)
           {
                   JOptionPane.showMessageDialog(null,"Duplicate Username or Password Access denied");
            }
           else
           {
               JOptionPane.showMessageDialog(null,"Username and Password is not correct");
           }   
          }
            else if(access=="HR")
            { 
                   if(count ==1)
                   {
                     JOptionPane.showMessageDialog(null,"Sucess.. WELCOME TO USER MENU");
                     UserMenu j = new UserMenu();
                     j.setVisible (true); 
                     this.dispose();
                    }
                else
                   {
                     JOptionPane.showMessageDialog(null,"Username and Password is not correct"); 
                   }     
            }
        }
        catch(Exception e)
        {
             JOptionPane.showMessageDialog(null, e);

        }
        finally {
            
            try{
                rs.close();
                pst.close(); 
            }
            catch(Exception e){     
            }
        }
    }
    }//GEN-LAST:event_btnSignInActionPerformed

    private void btnLoginAsDeveloperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginAsDeveloperActionPerformed
        // TODO add your handling code here:
        try{ 
           String sql = "select * from User_Authentication Where (Username =? and Password =? and Division =?)";
           int count =0;
           pst=con.prepareStatement(sql);
           pst.setString(1,txtUsername.getText());
           pst.setString(2,txtPassword.getText());
           pst.setString(3, cmbDivision.getSelectedItem().toString());
           rs=pst.executeQuery();
           while(rs.next())
           {   int UserId = rs.getInt(1);
               Emp.EmpId = UserId;
               String Username = rs.getString("Username");
               Emp.EmpName = Username;
           count =count+1;
           }
          String access=(cmbDivision.getSelectedItem().toString());
           if(access=="Admin") {
               if(count==1){
                   JOptionPane.showMessageDialog(null,"Sucess.. Loading Add System User Form...");
                   Users j = new Users();
                   j.setVisible(true);
                   this.dispose();}}      
    else 
    {
       JOptionPane.showMessageDialog(null, "Invalid User" , " Login Page", JOptionPane.ERROR_MESSAGE);
    }}                                      
catch(Exception ex){   
    JOptionPane.showMessageDialog(null,"Error Login to System"+ex);  
} 
    }//GEN-LAST:event_btnLoginAsDeveloperActionPerformed

    private void MenuItem_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem_ExitActionPerformed
        // TODO add your handling code here:
        int p = JOptionPane.showConfirmDialog(null, "Are you sure you want to Exit the System?",
                "Option Form",JOptionPane.YES_NO_OPTION);
        if(p==0){
        JOptionPane.showMessageDialog(null,"System Exiting...","Option Form",JOptionPane.ERROR_MESSAGE);
        System.exit(0); }
    }//GEN-LAST:event_MenuItem_ExitActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
         txtUsername.setText("");
         txtPassword.setText("");
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuItem_Exit;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnLoginAsDeveloper;
    private javax.swing.JButton btnSignIn;
    private javax.swing.JComboBox cmbDivision;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu lblDate;
    private javax.swing.JMenu lblTime;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
